from pathlib import Path

import tskit
import msprime
import pyslim
import pandas as pd
import math
import numpy as np
import csv

def calculate_diversity_and_divergence(ts, genome_indicies, time, output_diversities_path,
                                       output_divergences_path, output_fst_path,
                                       output_relatedness_path):
    '''
    Calculate diversity, divergence, Fst and genetic relatedness for given genome indices at a
    specific time from a tree sequence and output them to csv files.

    Parameters:
    ts: tree sequence object
    genome_indicies: list of population indices to sample from
    time: time point to sample
    output_diversities_path: file path to save diversities (pi, per subpop)
    output_divergences_path: file path to save divergences (d_xy, pairwise) -- diagnostic only
    output_fst_path: file path to save Fst (pairwise, relative differentiation)
    output_relatedness_path: file path to save genetic relatedness (pairwise, per-year centred)
    '''

    #Get all the nodes we are trying to sample from
    pop_samples = []
    for idx in genome_indicies:
        pop_samples.append(ts.samples(population=idx, time=time))

    K = len(pop_samples)
    pairs = [(i, j) for i in range(K) for j in range(K) if i != j]

    #Diversity (pi) per subpop -- all sample sets in a single traversal.
    diversities = np.asarray(ts.diversity(pop_samples), dtype=float)

    #Divergence (d_xy) -- ALL pairs in one traversal via indexes= (verified bit-identical to
    #per-pair calls, and ~orders of magnitude faster). Diagonal stays 0.
    #
    #Fst is HUDSON, computed here from pi and d_xy rather than by ts.Fst (CLAUDE.md 6.7):
    #
    #    Fst_Hudson = 1 - Hw / d_xy,      Hw = (pi_X + pi_Y)/2
    #
    #ts.Fst is DELIBERATELY NOT USED. It implements Nei (1973) / Slatkin (1991),
    #    Fst_Nei = 1 - 2(pi_X + pi_Y)/(pi_X + 2 d_xy + pi_Y) = (d_xy - Hw)/(d_xy + Hw),
    #which is a DIFFERENT quantity -- about HALF of Hudson at low differentiation, since
    #Hudson = (d_xy - Hw)/d_xy and the two denominators differ by the factor (1 + Hw/d_xy) ~ 2.
    #The empirical target is pixy's Weir-Cockerham (ToUseOnBeagles/AverageData.py), and WC and
    #Hudson estimate the SAME parameter -- measured agreeing to 1-5% on a known-truth msprime
    #2-deme model, against Nei/Hudson = 0.5027 on the same data. Fitting Nei against WC compared
    #two different statistics and cost a factor of ~2 in the inferred POPMULT (6.7).
    #
    #Free: pi and d_xy are already in hand, so this drops the ts.Fst traversal rather than
    #adding one. Fst is relative differentiation (~mu-invariant); computing it jointly here is
    #fine -- the centring footgun is relatedness-specific (CLAUDE.md 8#2), not an Fst concern.
    divergences = np.zeros((K, K))
    fsts = np.zeros((K, K))
    if pairs:
        div_flat = ts.divergence(pop_samples, indexes=pairs)
        for (i, j), dv in zip(pairs, div_flat):
            divergences[i, j] = dv
            # dv == 0 only for a degenerate pair (no variation at all); leave Fst at 0 rather
            # than emitting a NaN/inf that would silently poison fst_loss downstream.
            fsts[i, j] = 0.0 if dv == 0 else 1.0 - 0.5 * (diversities[i] + diversities[j]) / dv

    #Genetic relatedness, centred across THIS year's subpops by passing all sample sets to a
    #single call (matches empirical per-year centring; never slice a larger matrix --
    #CLAUDE.md 7#2/7#3). Reproduces CalcGenRel.py / tskit genetic_relatedness defaults.
    gr_indexes = [(i, j) for i in range(K) for j in range(K)]
    gr = ts.genetic_relatedness(pop_samples, indexes=gr_indexes)
    relatedness = np.asarray(gr, dtype=float).reshape(K, K)

    #write the data
    with open(output_diversities_path, "w", newline="") as f:
        writer = csv.writer(f)
        for item in diversities:
            writer.writerow([item])

    with open(output_divergences_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerows(divergences.tolist())

    with open(output_fst_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerows(fsts.tolist())

    with open(output_relatedness_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerows(relatedness.tolist())



def analyze_tree_sequence(mutation_rate=None, recombination_rate=None, ancestral_Ne=6700):
    '''
    This function analyzes the tree sequence file generated by the SLiM simulation by
    calculating diversity and divergence statistics before and after recapitation and mutation addition.
    It outputs the results to CSV files.

    mutation_rate, recombination_rate: REQUIRED, no defaults. See the guard below.

    ancestral_Ne: effective size of the panmictic ancestral population used in recapitation.
    Fixed empirical point estimate (6700); exposed here for sensitivity analysis only, NOT
    inferred -- it is confounded with mu via pi = 4*Ne*mu. See CLAUDE.md 5.1.
    '''
    # No defaults for mutation_rate/recombination_rate. The previous ones (1e-7 and 1e-8) were
    # BOTH known-wrong scales: 1e-8 is the pre-6.3 hardcoded forward recombination value, and
    # neither matches the calibrated mu (4.646e-7, 6.1.1) or the Cohen WI rate (2.75e-6). These
    # two numbers set the diversity and linkage scales of every output file, and those files
    # carry no record of which scale they are on -- so a silent fallback is worse than a crash
    # (CLAUDE.md 10).
    if mutation_rate is None or recombination_rate is None:
        raise ValueError(
            "analyze_tree_sequence() requires explicit mutation_rate and recombination_rate. "
            "Use ABCAnalysisNoRedis.DEFAULT_MUTATION_RATE (4.646e-7) and "
            "DEFAULT_RECOMBINATION_RATE (2.75e-6). See CLAUDE.md 6.1.1 and 6.3.")

    
    # Load the cluster_data CSV file
    cluster_data = pd.read_csv(Path("../data/cluster_data.csv"))

    assignments_2015 = cluster_data['Genome Assignment 2015']
    assignments_2019 = cluster_data['Genome Assignment 2019']
    assignments_2023 = cluster_data['Genome Assignment 2023']

    total_assignments_2015 = int(max(assignments_2015.dropna()))
    total_assignments_2019 = int(max(assignments_2019.dropna()))
    total_assignments_2023 = int(max(assignments_2023.dropna()))

    genome_indicies_2015 = [-1] * (total_assignments_2015+1)
    genome_indicies_2019 = [-1] * (total_assignments_2019+1)
    genome_indicies_2023 = [-1] * (total_assignments_2023+1)
    
    
    for i in range(len(assignments_2015)):
        if math.isnan(assignments_2015[i]) == False:
            index = int(assignments_2015[i])
            if genome_indicies_2015[index] == -1:
                genome_indicies_2015[index] = i
    for i in range(len(assignments_2019)):
        if math.isnan(assignments_2019[i]) == False:
            index = int(assignments_2019[i])
            if genome_indicies_2019[index] == -1:
                genome_indicies_2019[index] = i
    for i in range(len(assignments_2023)):
        if math.isnan(assignments_2023[i]) == False:
            index = int(assignments_2023[i])
            if genome_indicies_2023[index] == -1:
                genome_indicies_2023[index] = i

    # Load the tree sequence file
    ts = tskit.load(Path("../out/simTreeSeq.trees"))
    

    ts = pyslim.recapitate(ts, recombination_rate=recombination_rate, ancestral_Ne=ancestral_Ne)
    
    
    print("Simplifying tree sequence...")
    samplesToKeep = []
    for idx in genome_indicies_2015:
        samplesToKeep.extend(ts.samples(population=idx, time=16))
    for idx in genome_indicies_2019:
        samplesToKeep.extend(ts.samples(population=idx, time=8))
    for idx in genome_indicies_2023:
        samplesToKeep.extend(ts.samples(population=idx, time=0))
    
    
    # filter_populations=False is REQUIRED: the default (True) drops unreferenced populations and
    # renumbers the survivors to be contiguous, which breaks the ts.samples(population=idx) queries
    # in calculate_diversity_and_divergence (idx = original cluster-row index). With many demes
    # (e.g. numClusters=99) some are unreferenced after simplify -> renumbering -> a high original
    # index falls out of range -> empty sample set -> "Sample sets must contain at least one
    # element". Keeping population indices stable also guarantees correct per-subpop stats at every
    # cluster count (renumbering would otherwise silently map queries to the wrong deme).
    ts = ts.simplify(samples=samplesToKeep, filter_populations=False)
    
    next_id = pyslim.next_slim_mutation_id(ts)
    print("Simulating mutations...")
    ts = msprime.sim_mutations(
            ts,
            rate=mutation_rate,
            model=msprime.SLiMMutationModel(type=0, next_id=next_id),
            keep=True,
    )

    calculate_diversity_and_divergence(
        ts, genome_indicies_2023, time=0,
        output_diversities_path=Path("../data/Output_Data/diversities_2023.csv"),
        output_divergences_path=Path("../data/Output_Data/divergences_2023.csv"),
        output_fst_path=Path("../data/Output_Data/fst_2023.csv"),
        output_relatedness_path=Path("../data/Output_Data/relatedness_2023.csv"))

    calculate_diversity_and_divergence(
        ts, genome_indicies_2019, time=8,
        output_diversities_path=Path("../data/Output_Data/diversities_2019.csv"),
        output_divergences_path=Path("../data/Output_Data/divergences_2019.csv"),
        output_fst_path=Path("../data/Output_Data/fst_2019.csv"),
        output_relatedness_path=Path("../data/Output_Data/relatedness_2019.csv"))

    calculate_diversity_and_divergence(
        ts, genome_indicies_2015, time=16,
        output_diversities_path=Path("../data/Output_Data/diversities_2015.csv"),
        output_divergences_path=Path("../data/Output_Data/divergences_2015.csv"),
        output_fst_path=Path("../data/Output_Data/fst_2015.csv"),
        output_relatedness_path=Path("../data/Output_Data/relatedness_2015.csv"))
    
