from pathlib import Path

import tskit
import msprime
import pyslim
import pandas as pd
import math
import numpy as np
import csv

def calculate_diversity_and_divergence(ts, genome_indicies, time, output_diversities_path,
                                       output_divergences_path, output_fst_path,
                                       output_relatedness_path):
    '''
    Calculate diversity, divergence, Fst and genetic relatedness for given genome indices at a
    specific time from a tree sequence and output them to csv files.

    Parameters:
    ts: tree sequence object
    genome_indicies: list of population indices to sample from
    time: time point to sample
    output_diversities_path: file path to save diversities (pi, per subpop)
    output_divergences_path: file path to save divergences (d_xy, pairwise) -- diagnostic only
    output_fst_path: file path to save Fst (pairwise, relative differentiation)
    output_relatedness_path: file path to save genetic relatedness (pairwise, per-year centred)
    '''

    #Get all the nodes we are trying to sample from
    pop_samples = []
    for idx in genome_indicies:
        pop_samples.append(ts.samples(population=idx, time=time))

    K = len(pop_samples)
    pairs = [(i, j) for i in range(K) for j in range(K) if i != j]

    #Diversity (pi) per subpop -- all sample sets in a single traversal.
    diversities = np.asarray(ts.diversity(pop_samples), dtype=float)

    #Divergence (d_xy) and Fst -- ALL pairs in one traversal each via indexes= (verified
    #bit-identical to per-pair calls, and ~orders of magnitude faster). Diagonal stays 0.
    #Fst is relative differentiation (~mu-invariant); computed jointly here is fine -- the
    #centring footgun is relatedness-specific (CLAUDE.md 7#2), not an Fst/divergence concern.
    divergences = np.zeros((K, K))
    fsts = np.zeros((K, K))
    if pairs:
        div_flat = ts.divergence(pop_samples, indexes=pairs)
        fst_flat = ts.Fst(pop_samples, indexes=pairs)
        for (i, j), dv, fv in zip(pairs, div_flat, fst_flat):
            divergences[i, j] = dv
            fsts[i, j] = fv

    #Genetic relatedness, centred across THIS year's subpops by passing all sample sets to a
    #single call (matches empirical per-year centring; never slice a larger matrix --
    #CLAUDE.md 7#2/7#3). Reproduces CalcGenRel.py / tskit genetic_relatedness defaults.
    gr_indexes = [(i, j) for i in range(K) for j in range(K)]
    gr = ts.genetic_relatedness(pop_samples, indexes=gr_indexes)
    relatedness = np.asarray(gr, dtype=float).reshape(K, K)

    #write the data
    with open(output_diversities_path, "w", newline="") as f:
        writer = csv.writer(f)
        for item in diversities:
            writer.writerow([item])

    with open(output_divergences_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerows(divergences.tolist())

    with open(output_fst_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerows(fsts.tolist())

    with open(output_relatedness_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerows(relatedness.tolist())



def analyze_tree_sequence(mutation_rate=1e-7, recombination_rate=1e-8, ancestral_Ne=6700):
    '''
    This function analyzes the tree sequence file generated by the SLiM simulation by
    calculating diversity and divergence statistics before and after recapitation and mutation addition.
    It outputs the results to CSV files.

    ancestral_Ne: effective size of the panmictic ancestral population used in recapitation.
    Fixed empirical point estimate (6700); exposed here for sensitivity analysis only, NOT
    inferred -- it is confounded with mu via pi = 4*Ne*mu. See CLAUDE.md 5.1.
    '''
    
    # Load the cluster_data CSV file
    cluster_data = pd.read_csv(Path("../data/cluster_data.csv"))

    assignments_2015 = cluster_data['Genome Assignment 2015']
    assignments_2019 = cluster_data['Genome Assignment 2019']
    assignments_2023 = cluster_data['Genome Assignment 2023']

    total_assignments_2015 = int(max(assignments_2015.dropna()))
    total_assignments_2019 = int(max(assignments_2019.dropna()))
    total_assignments_2023 = int(max(assignments_2023.dropna()))

    genome_indicies_2015 = [-1] * (total_assignments_2015+1)
    genome_indicies_2019 = [-1] * (total_assignments_2019+1)
    genome_indicies_2023 = [-1] * (total_assignments_2023+1)
    
    
    for i in range(len(assignments_2015)):
        if math.isnan(assignments_2015[i]) == False:
            index = int(assignments_2015[i])
            if genome_indicies_2015[index] == -1:
                genome_indicies_2015[index] = i
    for i in range(len(assignments_2019)):
        if math.isnan(assignments_2019[i]) == False:
            index = int(assignments_2019[i])
            if genome_indicies_2019[index] == -1:
                genome_indicies_2019[index] = i
    for i in range(len(assignments_2023)):
        if math.isnan(assignments_2023[i]) == False:
            index = int(assignments_2023[i])
            if genome_indicies_2023[index] == -1:
                genome_indicies_2023[index] = i

    # Load the tree sequence file
    ts = tskit.load(Path("../out/simTreeSeq.trees"))
    

    ts = pyslim.recapitate(ts, recombination_rate=recombination_rate, ancestral_Ne=ancestral_Ne)
    
    
    print("Simplifying tree sequence...")
    samplesToKeep = []
    for idx in genome_indicies_2015:
        samplesToKeep.extend(ts.samples(population=idx, time=16))
    for idx in genome_indicies_2019:
        samplesToKeep.extend(ts.samples(population=idx, time=8))
    for idx in genome_indicies_2023:
        samplesToKeep.extend(ts.samples(population=idx, time=0))
    
    
    ts = ts.simplify(samples=samplesToKeep)
    
    next_id = pyslim.next_slim_mutation_id(ts)
    print("Simulating mutations...")
    ts = msprime.sim_mutations(
            ts,
            rate=mutation_rate,
            model=msprime.SLiMMutationModel(type=0, next_id=next_id),
            keep=True,
    )

    calculate_diversity_and_divergence(
        ts, genome_indicies_2023, time=0,
        output_diversities_path=Path("../data/Output_Data/diversities_2023.csv"),
        output_divergences_path=Path("../data/Output_Data/divergences_2023.csv"),
        output_fst_path=Path("../data/Output_Data/fst_2023.csv"),
        output_relatedness_path=Path("../data/Output_Data/relatedness_2023.csv"))

    calculate_diversity_and_divergence(
        ts, genome_indicies_2019, time=8,
        output_diversities_path=Path("../data/Output_Data/diversities_2019.csv"),
        output_divergences_path=Path("../data/Output_Data/divergences_2019.csv"),
        output_fst_path=Path("../data/Output_Data/fst_2019.csv"),
        output_relatedness_path=Path("../data/Output_Data/relatedness_2019.csv"))

    calculate_diversity_and_divergence(
        ts, genome_indicies_2015, time=16,
        output_diversities_path=Path("../data/Output_Data/diversities_2015.csv"),
        output_divergences_path=Path("../data/Output_Data/divergences_2015.csv"),
        output_fst_path=Path("../data/Output_Data/fst_2015.csv"),
        output_relatedness_path=Path("../data/Output_Data/relatedness_2015.csv"))
    
